# This workflow will do a clean installation of node dependencies, cache/restore them and build the source code
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Installing dependencies
      uses: borales/actions-yarn@v3.0.0
      with:
        cmd: install # will run `yarn install` command
    - name: Building App
      uses: borales/actions-yarn@v3.0.0
      with:
        cmd: build # will run `yarn build` command
